# Generated by Django 5.1.5 on 2025-07-18 08:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('repertoire', models.JSONField(blank=True, default=api.models.default_repertoire)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
