# Generated by Django 5.2.4 on 2025-07-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='repertoire',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
