# Generated by Django 5.1.5 on 2025-07-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='appuser',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
