# Generated by Django 5.2.4 on 2025-07-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appuser_repertoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='repertoire',
            field=models.JSONField(blank=True, default={'allPieces': []}),
        ),
    ]
